### PR TITLE
Fix strpos needle conversion in PHP > 7.3.0

### LINKED ISSUE #2: PHP deprecation notice in 7.3
I'm getting the following notice using PHP 7.3 
```
NOTICE: PHP message: PHP Deprecated:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /app/vendor/wikimedia/less.php/lib/Less/SourceMap/Generator.php on line 172
```

Doesn't seem urgent but hast to be fixed eventually.
Affected line:
https://github.com/Asenar/less.php/blob/master/lib/Less/SourceMap/Generator.php#L172

### PR DESCRIPTION
**Pull request by schliflo**
Fixes #2

### CODE REVIEW

**Comment by Asenar** [comment]
Thanks :)

How can I reproduce the notice you got in #2  ?

If `$basePath` is not a string, what is it in your case ? `null` or `false` ? what if the basePath (which is supposed to be a directory) is a number ?

Maybe it can be better to replace `if (strpos($filename, $basePath) === 0)` by `if (is_string($basePath) && strpos($filename, $basePath) === 0)` ?

**Comment by schliflo** [comment]
`$basePath` is `null` in my case. I'll update it to `(is_string($basePath) && strpos($filename, $basePath) === 0)`

**Comment by Asenar** [comment]
I integrated your changes in `develop` branch. If you want to use it with composer you can use `dev-develop` instead of pointing version `1.8.0` if it's ok for you.

**Comment by schliflo** [comment]
ok, thank you

**Pull request closed without merging**
